import { useState } from "react";
import { Copy, Check, Code2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import type { VisualType } from "./VisualTypeSelector";
import type { VisualProperties } from "./PropertyPanel";
import type { DataPoint } from "./DataEditor";

interface CodeExportProps {
  type: VisualType;
  data: DataPoint[];
  properties: VisualProperties;
}

export function CodeExport({ type, data, properties }: CodeExportProps) {
  const [copied, setCopied] = useState(false);

  const generateCode = () => {
    const dataStr = JSON.stringify(
      data.map((d) => ({ name: d.category, value: d.value })),
      null,
      2
    );

    return `// Power BI Visual Configuration
// Generated by Power BI Visual Builder

export const visualConfig = {
  type: "${type}",
  properties: {
    title: "${properties.title}",
    showTitle: ${properties.showTitle},
    showLegend: ${properties.showLegend},
    showDataLabels: ${properties.showDataLabels},
    primaryColor: "${properties.primaryColor}",
    backgroundColor: "${properties.backgroundColor}",
    fontSize: ${properties.fontSize},
    borderRadius: ${properties.borderRadius},
    animationDuration: ${properties.animationDuration},
  },
  data: ${dataStr},
};

// Power BI Visual API Implementation
export class Visual implements IVisual {
  private target: HTMLElement;
  
  constructor(options: VisualConstructorOptions) {
    this.target = options.element;
    this.init();
  }

  private init() {
    // Initialize your ${type} chart here
    // Use visualConfig for settings
  }

  public update(options: VisualUpdateOptions) {
    // Update visualization with new data
    const dataView = options.dataViews[0];
    // Process dataView and render chart
  }
}`;
  };

  const copyToClipboard = async () => {
    await navigator.clipboard.writeText(generateCode());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button className="gap-2 gradient-powerbi text-primary-foreground hover:opacity-90">
          <Code2 className="h-4 w-4" />
          Export Code
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-2xl max-h-[80vh]">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Code2 className="h-5 w-5 text-accent" />
            Power BI Visual Code
          </DialogTitle>
        </DialogHeader>
        <div className="relative">
          <pre className="bg-sidebar text-sidebar-foreground p-4 rounded-lg overflow-auto max-h-[50vh] text-sm font-mono">
            <code>{generateCode()}</code>
          </pre>
          <Button
            size="sm"
            variant="secondary"
            onClick={copyToClipboard}
            className="absolute top-2 right-2 gap-2"
          >
            {copied ? (
              <>
                <Check className="h-4 w-4 text-success" />
                Copied!
              </>
            ) : (
              <>
                <Copy className="h-4 w-4" />
                Copy
              </>
            )}
          </Button>
        </div>
        <p className="text-sm text-muted-foreground">
          Use this configuration with the Power BI Visuals SDK to create your custom visual.
        </p>
      </DialogContent>
    </Dialog>
  );
}
